
persistence:
  enabled: true
  size: 1Gi

datasources:
  datasource.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prom-prometheus-server:80
        isDefault: true
        version: 2
        editable: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: 'default'
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    prometheus_overview:
      gnetId: 159  # Grafana's ID for the Prometheus Overview dashboard
      revision: 5
      datasource: Prometheus