apiVersion: apps/v1
kind: Deployment
metadata:
  name: segole
  labels:
    app: segole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: segole
  template:
    metadata:
        labels:
          app: segole
    spec:
      containers:
      - name: server
        image: maayanassraf/segole:1.0.3
        ports:
          - containerPort: 3000
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi